# Generated by Django 4.0 on 2022-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to=''),
        ),
    ]
